framework:
    cache:
        enable_annotations: true
        prefix_seed: app_
        app: cache.adapter.redis
        system: cache.adapter.redis
        default_redis_provider: 'snc_redis.default'
