framework:
    secret: '%env(APP_SECRET)%'
    csrf_protection: true
    http_method_override: true

    session:
        handler_id: Symfony\Component\HttpFoundation\Session\Storage\Handler\RedisSessionHandler
        cookie_secure: auto
        cookie_samesite: strict
        name: eland
        sid_bits_per_character: 5
        cookie_lifetime: 2592000 # 30 days
        gc_maxlifetime: 864000 # 10 days

    #esi: true
    #fragments: true
    php_errors:
        log: true
