framework:
    messenger:
        # Uncomment this (and the failed transport below) to send failed messages to this transport for later handling.
        # failure_transport: failed
        transports:
            sync: sync://
            mail_lo:
                dsn: redis://
                options:
                    client: snc_redis.messages
                    stream: mail_lo
            mail_hi:
                dsn: redis://
                options:
                    client: snc_redis.messages
                    stream: mail_hi
            async:
                dsn: redis://
                options:
                    client: snc_redis.messages
                    stream: async
                retry_strategy:
                    max_retries: 5
                    delay: 2000
                    multiplier: 2
                    max_delay: 10000
            images:
                dsn: redis://
                options:
                    client: snc_redis.messages
                    stream: images
            geo:
                dsn: redis://
                options:
                    client: snc_redis.messages
                    stream: geo
            # https://symfony.com/doc/current/messenger.html#transport-configuration
            # async: '%env(MESSENGER_TRANSPORT_DSN)%'
            # default:
            #  dsn: 'doctrine://default'
            #  options:
            #    table_name: 'xdb.messenger_messages'
            # sync: 'sync://'

        #routing:
            # Route your messages to the transports
            # 'App\Message\YourMessage': async

# when@test:
#    framework:
#        messenger:
#            transports:
#                # replace with your transport name here (e.g., my_transport: 'in-memory://')
#                # For more Messenger testing tools, see https://github.com/zenstruck/messenger-test
#                async: 'in-memory://'
