framework:
  messenger:
    # Uncomment this (and the failed transport below) to send failed messages to this transport for later handling.
    # failure_transport: failed
    transports:
      sync: sync://
      mail_lo:
        dsn: '%env(REDIS_URL)%/10'
        options:
          stream: mail_lo
      mail_mi:
        dsn: '%env(REDIS_URL)%/10'
        options:
          stream: mail_mi
      mail_hi:
        dsn: '%env(REDIS_URL)%/10'
        options:
          stream: mail_hi
      mail_dispatch:
        dsn: '%env(REDIS_URL)%/10'
        options:
          stream: mail_dispatch
      async:
        dsn: '%env(REDIS_URL)%/10'
        options:
          stream: async
        retry_strategy:
          max_retries: 5
          delay: 2000
          multiplier: 2
          max_delay: 10000
      images:
        dsn: '%env(REDIS_URL)%/10'
        options:
          stream: images
      geo:
        dsn: '%env(REDIS_URL)%/10'
        options:
          stream: geo
        retry_strategy:
          max_retries: 5
          delay: 60000            # Wait 60 seconds before retry
          multiplier: 2           # 60s, 120s, 240s
          max_delay: 3600000      # 1 hour

    # async routing is handled in wrapper \App\Email\Message\EmailDispatchMessage
    routing:
      Symfony\Component\Mailer\Messenger\SendEmailMessage: mail_dispatch

# when@test:
#    framework:
#        messenger:
#            transports:
#                # replace with your transport name here (e.g., my_transport: 'in-memory://')
#                # For more Messenger testing tools, see https://github.com/zenstruck/messenger-test
#                async: 'in-memory://'
