security:
    encoders:
        App\Security\User:
            algorithm: auto
    providers:
        # used to reload user from session & other features (e.g. switch_user)
        app_user_provider:
            id: App\Security\UserProvider
    firewalls:
        dev:
            pattern: ^/(_profiler|_wdt)/
            security: false
        main:
            anonymous: true
            access_denied_handler: App\Security\AccessDeniedHandler

#            guard:
#                authenticators:
#                    - App\Security\LoginAuthenticator
#                    - App\Security\SystemUserAuthenticator
#                entry_point: App\Security\SystemUserAuthenticator
#            logout:
#                path: logout
                # where to redirect after logout
                # target: login

    access_control:
         - { path: ^/\w+/a/, roles: admin }
         - { path: ^/\w+/u/, roles: user }
         - { path: ^/\w+/g/, roles: guest }

#    role_hierarchy:
#        ROLE_MASTER: ROLE_ADMIN
#        ROLE_ADMIN: [ROLE_USER, ROLE_ALLOWED_TO_SWITCH]
#        ROLE_USER: ROLE_GUEST
#        ROLE_ELAS_GUEST: ROLE_GUEST
