snc_redis:
    clients:
        default:
            type: phpredis
            alias: default
            # See https://github.com/snc/SncRedisBundle/issues/709
            dsn: '%env(temp_redis_dsn_fix:REDIS_URL)%'
            logging: '%kernel.debug%'
            options:
                prefix: eland_

#        monolog:
#            type: phpredis
#            alias: monolog
#            dsn: '%env(REDIS_URL)%'
#            logging: false
#            options:
#                connection_persistent: true
#                prefix: eland_
#    monolog:
#        client: monolog
#        key: monolog_logs
