snc_redis:
    clients:
        default:
            type: phpredis
            alias: default
            dsn: '%env(REDIS_URL)%'
            logging: '%kernel.debug%'
            options:
                prefix: eland_
    session:
        client: default
        prefix: session_
