snc_redis:
    clients:
        default:
            type: phpredis
            alias: default
            # See https://github.com/snc/SncRedisBundle/issues/709
            dsn: '%env(temp_redis_dsn_fix:REDIS_URL)%'
            logging: '%kernel.debug%'
            options:
                prefix: eland.
        monolog:
            type: phpredis
            alias: monolog
            # See https://github.com/snc/SncRedisBundle/issues/709
            dsn: '%env(temp_redis_dsn_fix:REDIS_URL)%'
            logging: false #'%kernel.debug%'
            options:
                prefix: eland.
    monolog:
        client: monolog
        key: monolog
        formatter: monolog.formatter.json
