symfonycasts_sass:
  root_sass:
    - '%kernel.project_dir%/assets/styles/bs3.scss'
    - '%kernel.project_dir%/assets/styles/email.scss'
  sass_options:
    load_path:
      - '%kernel.project_dir%/node_modules'