framework:
    validation:
        enabled: true
        enable_annotations: true
        cache: validator.mapping.cache.doctrine.apc
        email_validation_mode: html5

        # Enables validator auto-mapping support.
        # For instance, basic validation constraints will be inferred from Doctrine's metadata.
        #auto_mapping:
        #    App\Entity\: []
