#!/bin/bash
if [ -z "$1" ]; then
    if [ -f .local ] && [ -e .local ]; then
        LOCAL="$(head -n 1 .local )"
    else
        LOCAL=localhost:8888
    fi
else
  LOCAL=$1
fi
eval "$( cat .env_m | tr  '\n' ' ' )" php -d variables_order=EGPCS -S $LOCAL
