monolog:
    handlers:
        stream:
            path: "php://stdout"
            type: stream
            level: debug
            formatter: Bramus\Monolog\Formatter\ColoredLineFormatter
            channels: ["app"]
        redis:
            type: service
            id: App\Monolog\RedisHandler
            level: debug
            channels: ["app"]
        console:
            type: console
            process_psr_3_messages: false
