monolog:
    use_microseconds: false
    handlers:
        stream:
            path: "php://stdout"
            type: stream
            level: info
            formatter: Bramus\Monolog\Formatter\ColoredLineFormatter
            #channels: ["app"]
        redis:
            type: service
            id: snc_redis.monolog.handler
            level: debug
            channels: ["app"]
        console:
            type: console
            process_psr_3_messages: false