parameters:
    router.request_context.host: '%env(APP_HOST)%'
    router.request_context.scheme: '%env(APP_SCHEME)%'
    app.default_locale: nl
    app.locales: en|nl
    assert.elas_token: '[0-9a-f]{32}'
    assert.token: '[a-z0-9-]{12}'
    assert.system: '[a-z][a-z0-9]*'
    assert.schema: '[a-z][a-z0-9]*'
    assert.role_short.guest: '[gua]'
    assert.role_short.user: '[ua]'
    assert.role_short.admin: 'a'
    assert.id: \d++
    assert.doc_id: '[0-9a-f]{24}'
    assert.view: 'extended|list|map|tiles'
    assert.config_tab: 'system-name|logo|currency|mail-addr|balance|periodic-mail|contact|register|messages|users|news|forum|system'
    assert.account_status: 'active|new|leaving|inactive|im|ip|extern|all'
    assert.account_status.primary: 'active|inactive|im|ip|extern'
    assert.account_status.active: 'active|new|leaving'
    assert.message_image: '[a-z][a-z0-9]*_m_\d+_[a-f0-9]{40}'
    assert.message_image_ext: 'jpg|png|gif'


services:
    _defaults:
        autowire: true
        autoconfigure: true
        bind:
            $env_mapbox_token: '%env(MAPBOX_TOKEN)%'
            $env_legacy_eland_origin_pattern: '%env(LEGACY_ELAND_ORIGIN_PATTERN)%'
            $env_aws_s3_bucket: '%env(AWS_S3_BUCKET)%'
            $env_aws_s3_region: '%env(AWS_S3_REGION)%'
            $env_s3_url: 'https://s3.%env(AWS_S3_REGION)%.amazonaws.com/%env(AWS_S3_BUCKET)%/'
            $env_mail_noreply_address: '%env(MAIL_NOREPLY_ADDRESS)%'
            $env_mail_from_address: '%env(MAIL_FROM_ADDRESS)%'
            $env_mail_hoster_address: '%env(MAIL_HOSTER_ADDRESS)%'
            $env_master_password: '%env(MASTER_PASSWORD)%'
            $env_mollie_test_api_key: '%env(MOLLIE_TEST_API_KEY)%'
            $env_google_geo_api_key: '%env(GOOGLE_GEO_API_KEY)%'
            $env_app_host: '%env(APP_HOST)%'
            $env_app_scheme: '%env(APP_SCHEME)%'

    App\:
        resource: '../src/*'
        exclude: '../src/{DependencyInjection,Entity,Migrations,Tests,Kernel.php}'

    App\Controller\:
        resource: '../src/Controller'
        tags: ['controller.service_arguments']

    App\Service\SessionUserService:
        lazy: true

    Predis\Client:
        arguments:
            - '%env(REDIS_URL)%'
            - {prefix: eland_}

    Symfony\Component\HttpFoundation\Session\Storage\Handler\RedisSessionHandler:
        arguments:
            - '@Predis\Client'
            - {prefix: session_}
