index_contact:
  path: /contact
  controller: App\Controller\IndexContactController::index_contact
  methods: GET|POST

monitor:
  path: /monitor
  controller: App\Controller\MonitorController::monitor
  methods: GET

system:
  prefix: /{system<%assert.system%>}
  resource: system.yaml

index:
  path: /
  controller: App\Controller\IndexController::index
  methods: GET
