index_contact:
  path: /contact
  controller: App\Controller\IndexContactController::index_contact

monitor:
  path: /monitor
  controller: App\Controller\MonitorController::monitor

system:
  prefix: /{system<%assert.system%>}
  resource: system.yaml

index:
  path: /
  controller: App\Controller\IndexController::index
