theme:
  path: /theme
  controller: Symfony\Bundle\FrameworkBundle\Controller\TemplateController
  defaults:
    template: theme/theme.html.twig

index_contact:
  path: /contact
  controller: App\Controller\Index\IndexContactController
  methods: GET|POST

monitor:
  path: /monitor
  controller: App\Controller\MonitorController
  methods: GET|HEAD

system:
  prefix: /{system<%assert.system%>}
  resource: system_anonymous.yaml

index:
  path: /
  controller: App\Controller\Index\IndexController
  methods: GET
