login:
  path: /login
  controller: App\Controller\LoginController
  methods: GET|POST

contact:
  path: /contact
  controller: App\Controller\ContactFormController
  methods: GET|POST

contact_token:
  path: /contact/{token<%assert.token%>}
  controller: App\Controller\ContactFormTokenController
  methods: GET

register:
  path: /register
  controller: App\Controller\RegisterController
  methods: GET|POST

register_token:
  path: /register/{token<%assert.token%>}
  controller: App\Controller\RegisterTokenController
  methods: GET

password_reset:
  path: /password-reset
  controller: App\Controller\PasswordResetController
  methods: GET|POST

password_reset_token:
  path: /password-reset/{token<%assert.token%>}
  controller: App\Controller\PasswordResetTokenController
  methods: GET|POST

mollie_webhook:
  path: /mollie/webhook
  controller: App\Controller\MollieWebhookController
  methods: GET

mollie_checkout_anonymous:
  path: /mollie/checkout/{token<%assert.big_token%>}
  controller: App\Controller\MollieCheckoutAnonymousController
  methods: GET|POST

mollie_status_anonymous:
  path: /mollie/status/{token<%assert.big_token%>}
  controller: App\Controller\MollieStatusAnonymousController
  methods: GET

system_admin:
  prefix: /{role_short<%assert.role_short.admin%>}
  resource: system_admin.yaml

system_user:
  prefix: /{role_short<%assert.role_short.user%>}
  resource: system_user.yaml

system_guest:
  prefix: /{role_short<%assert.role_short.guest%>}
  resource: system_guest.yaml

system_init:
  prefix: /init
  resource: system_init.yaml

home:
  path: /
  controller: App\Controller\HomeController
  methods: GET
