status:
  controller: App\Controller\StatusController
  path: /status
  methods: GET

categories_del:
  controller: App\Controller\Categories\CategoriesDelController
  path: /categories/{id<%assert.id%>}/del
  methods: GET|POST

categories_edit:
  controller: App\Controller\Categories\CategoriesEditController
  path: /categories/{id<%assert.id%>}/edit
  methods: GET|POST

categories_add:
  controller: App\Controller\Categories\CategoriesAddController
  path: /categories/add
  methods: GET|POST

categories:
  controller: App\Controller\Categories\CategoriesController
  path: /categories
  methods: GET

contact_types_del:
  controller: App\Controller\ContactTypes\ContactTypesDelController
  path: /contact-types/{id<%assert.id%>}/del
  methods: GET|POST

contact_types_edit:
  controller: App\Controller\ContactTypes\ContactTypesEditController
  path: /contact-types/{id<%assert.id%>}/edit
  methods: GET|POST

contact_types_add:
  controller: App\Controller\ContactTypes\ContactTypesAddController
  path: /contact-types/add
  methods: GET|POST

contact_types:
  controller: App\Controller\ContactTypes\ContactTypesController
  path: /contact-types
  methods: GET

contacts_del_admin:
  controller: App\Controller\Contacts\ContactsDelAdminController
  path: /contacts/{id<%assert.id%>}/del
  methods: GET|POST

contacts_edit_admin:
  controller: App\Controller\Contacts\ContactsEditAdminController
  path: /contacts/{id<%assert.id%>}/edit
  methods: GET|POST

contacts_add_admin:
  controller: App\Controller\Contacts\ContactsAddAdminController
  path: /contacts/add
  methods: GET|POST

contacts:
  controller: App\Controller\Contacts\ContactsAdminController
  path: /contacts
  methods: GET

users_contacts_edit_admin:
  controller: App\Controller\UsersContacts\UsersContactsEditAdminController
  path: /users/{user_id<%assert.id%>}/contacts/{contact_id<%assert.id%>}/edit
  methods: GET|POST

users_contacts_del_admin:
  controller: App\Controller\UsersContacts\UsersContactsDelAdminController
  path: /users/{user_id<%assert.id%>}/contacts/{contact_id<%assert.id%>}/del
  methods: GET|POST

users_contacts_add_admin:
  controller: App\Controller\UsersContacts\UsersContactsAddAdminController
  path: /users/{user_id<%assert.id%>}/contacts/add
  methods: GET|POST

config:
  controller: App\Controller\ConfigController
  path: /config/{tab<%assert.config_tab%>?system-name}
  methods: GET|POST

intersystems_edit:
  controller: App\Controller\IntersystemsEditController
  path: /intersystems/{id<%assert.id%>}/edit
  methods: GET|POST

intersystems_del:
  controller: App\Controller\IntersystemsDelController
  path: /intersystems/{id<%assert.id%>}/del
  methods: GET|POST

intersystems_add:
  controller: App\Controller\IntersystemsAddController
  path: /intersystems/add
  methods: GET|POST

intersystems_show:
  controller: App\Controller\IntersystemsShowController
  path: /intersystems/{id<%assert.id%>}
  methods: GET

intersystems:
  controller: App\Controller\IntersystemsController
  path: /intersystems
  methods: GET

export:
  controller: App\Controller\ExportController
  path: /export
  methods: GET

autominlimit:
  controller: App\Controller\AutoMinLimitController
  path: /autominlimit
  methods: GET|POST

mass_transaction:
  controller: App\Controller\MassTransactionController
  path: /mass-transaction
  methods: GET|POST

logs:
  controller: App\Controller\LogsController
  path: /logs
  methods: GET

users_image_del_admin:
  controller: App\Controller\UsersImage\UsersImageDelAdminController
  path: /users/{id<%assert.id%>}/image/del
  methods: GET|POST

users_image_upload_admin:
  controller: App\Controller\UsersImage\UsersImageUploadAdminController
  path: /users/{id<%assert.id%>}/image/upload
  methods: POST

users_password_admin:
  controller: App\Controller\Users\UsersPasswordAdminController
  path: /users/{id<%assert.id%>}/password
  methods: GET|POST

users_show_admin:
  controller: App\Controller\Users\UsersShowAdminController
  path: /users/{id<%assert.id%>}/{status<%assert.account_status%>?active}
  methods: GET|POST

users_del_admin:
  controller: App\Controller\Users\UsersDelAdminController
  path: /users/{id<%assert.id%>}/del
  methods: GET|POST

users_edit_admin:
  controller: App\Controller\Users\UsersEditAdminController
  path: /users/{id<%assert.id%>}/edit
  methods: GET|POST

users_add:
  controller: App\Controller\Users\UsersAddController
  path: /users/add
  methods: GET|POST

users_tiles_admin:
  controller: App\Controller\Users\UsersTilesAdminController
  path: /users/tiles/{status<%assert.account_status%>?active}
  methods: GET

users_list_admin:
  controller: App\Controller\Users\UsersListAdminController
  path: /users/{status<%assert.account_status%>?active}
  methods: GET|POST

transactions_edit:
  controller: App\Controller\Transactions\TransactionsEditController
  path: /transactions/{id<%assert.id%>}/edit
  methods: GET|POST

news_add:
  controller: App\Controller\News\NewsAddController
  path: /news/add
  methods: GET|POST

news_del:
  controller: App\Controller\News\NewsDelController
  path: /news/{id<%assert.id%>}/del
  methods: GET|POST

news_edit:
  controller: App\Controller\News\NewsEditController
  path: /news/{id<%assert.id%>}/edit
  methods: GET|POST

calendar_add:
  controller: App\Controller\CalendarAddController
  path: /calendar/add
  methods: GET|POST

calendar_del:
  controller: App\Controller\CalendarDelController
  path: /calendar/{id<%assert.id%>}/del
  methods: GET|POST

calendar_edit:
  controller: App\Controller\CalendarEditController
  path: /calendar/{id<%assert.id%>}/edit
  methods: GET|POST

docs_edit:
  controller: App\Controller\Docs\DocsEditController
  path: /docs/{id<%assert.id%>}/edit
  methods: GET|POST

docs_del:
  controller: App\Controller\Docs\DocsDelController
  path: /docs/{id<%assert.id%>}/del
  methods: GET|POST

docs_add:
  controller: App\Controller\Docs\DocsAddController
  path: /docs/add
  methods: GET|POST

docs_map_edit:
  controller: App\Controller\Docs\DocsMapEditController
  path: /docs/map/{id<%assert.id%>}/edit
  methods: GET|POST

typeahead_doc_map_names:
  controller: App\Controller\Typeahead\TypeaheadDocMapNamesController
  path: /typeahead-doc-map-names
  methods: GET

typeahead_log_types:
  controller: App\Controller\Typeahead\TypeaheadLogTypesController
  path: /typeahead-log-types
  methods: GET

transactions_sum_in:
  controller: App\Controller\TransactionsSumInController
  path: /transactions-sum-in/{days<%assert.id%>}
  methods: GET

transactions_sum_out:
  controller: App\Controller\TransactionsSumOutController
  path: /transactions-sum-out/{days<%assert.id%>}
  methods: GET

weighted_balances:
  controller: App\Controller\WeightedBalancesController
  path: /weighted-balances/{days<%assert.id%>}
  methods: GET

logo_upload:
  controller: App\Controller\LogoUploadController
  path: /logo/upload
  methods: POST

logo_del:
  controller: App\Controller\LogoDelController
  path: /logo/del
  methods: GET|POST

static_content_image_upload:
  controller: App\Controller\StaticContentImageUploadController
  path: /static-content/image-upload
  methods: POST

static_content:
  controller: App\Controller\StaticContentController
  path: /static-content
  methods: POST

login_admin:
  path: /login
  controller: App\Controller\LoginAdminController
  methods: GET

contact_admin:
  path: /contact
  controller: App\Controller\ContactFormAdminController
  methods: GET

register_admin:
  path: /register
  controller: App\Controller\RegisterAdminController
  methods: GET

password_reset_admin:
  path: /password-reset
  controller: App\Controller\PasswordResetAdminController
  methods: GET

home_admin:
  path: /
  controller: App\Controller\HomeAdminController
  methods: GET

mollie_config:
  path: /mollie/config
  controller: App\Controller\Mollie\MollieConfigController
  methods: GET|POST

mollie_payments_add:
  path: /mollie/payments/add/{status<%assert.account_status%>?active}
  controller: App\Controller\Mollie\MolliePaymentsAddController
  methods: GET|POST

mollie_payments:
  path: /mollie/payments
  controller: App\Controller\Mollie\MolliePaymentsController
  methods: GET|POST
