



login_elas_token:
  path: /login-elas/{elas_token<%assert.elas_token%>}
  controller: App\Controller\LoginElasController::login_elas_token
  methods: GET

login:
  path: /login
  controller: App\Controller\LoginController::login
  methods: GET|POST

contact:
  path: /contact
  controller: App\Controller\ContactController::contact
  methods: GET|POST

contact_token:
  path: /contact/{token<%assert.token%>}
  controller: App\Controller\ContactTokenController::contact_token
  methods: GET

register:
  path: /register
  controller: App\Controller\RegisterController::register
  methods: GET|POST

register_token:
  path: /register/{token<%assert.token%>}
  controller: App\Controller\RegisterTokenController::register_token
  methods: GET

password_reset:
  path: /password-reset
  controller: App\Controller\PasswordResetController::password_reset
  methods: GET|POST

password_reset_token:
  path: /password-reset/{token<%assert.token%>}
  controller: App\Controller\PasswordResetTokenController::password_reset_token
  methods: GET|POST

system_guest:
  prefix: /{role_short<%assert.role_short.guest%>}
  resource: system_guest.yaml

system_user:
  prefix: /{role_short<%assert.role_short.user%>}
  resource: system_user.yaml

system_admin:
  prefix: /{role_short<%assert.role_short.admin%>}
  resource: system_admin.yaml

home_system:
  path: /
  controller: App\Controller\HomeSystemController::home_system
  methods: GET
