login:
  path: /login
  controller: App\Controller\Auth\LoginController
  methods: GET|POST

contact_form:
  path: /contact
  controller: App\Controller\ContactForm\ContactFormController
  methods: GET|POST

contact_form_confirm:
  path: /contact/{token<%assert.token%>}
  controller: App\Controller\ContactForm\ContactFormConfirmController
  methods: GET

register:
  path: /register
  controller: App\Controller\Register\RegisterController
  methods: GET|POST

register_confirm:
  path: /register/{token<%assert.token%>}
  controller: App\Controller\Register\RegisterConfirmController
  methods: GET

password_reset_request:
  path: /password-reset
  controller: App\Controller\PasswordReset\PasswordResetRequestController
  methods: GET|POST

password_reset_set:
  path: /password-reset/{token<%assert.token%>}
  controller: App\Controller\PasswordReset\PasswordResetSetController
  methods: GET|POST

mollie_webhook:
  path: /mollie/webhook
  controller: App\Controller\Mollie\MollieWebhookController
  methods: POST

mollie_checkout_anonymous:
  path: /mollie/checkout/{token<%assert.big_token%>}
  controller: App\Controller\Mollie\MollieCheckoutAnonymousController
  methods: GET|POST

system_admin:
  prefix: /{role_short<%assert.role_short.admin%>}
  resource: system_admin.yaml

system_user:
  prefix: /{role_short<%assert.role_short.user%>}
  resource: system_user.yaml

system_guest:
  prefix: /{role_short<%assert.role_short.guest%>}
  resource: system_guest.yaml

system_init:
  prefix: /init
  resource: system_init.yaml

home:
  path: /
  controller: App\Controller\HomeController
  methods: GET
