login:
  path: /login
  controller: App\Controller\LoginController
  methods: GET|POST

contact_form:
  path: /contact
  controller: App\Controller\ContactFormController
  methods: GET|POST

contact_form_confirm:
  path: /contact/{token<%assert.token%>}
  controller: App\Controller\ContactFormConfirmController
  methods: GET

register_form:
  path: /register
  controller: App\Controller\RegisterFormController
  methods: GET|POST

register_form_confirm:
  path: /register/{token<%assert.token%>}
  controller: App\Controller\RegisterFormConfirmController
  methods: GET

password_reset:
  path: /password-reset
  controller: App\Controller\PasswordResetController
  methods: GET|POST

password_reset_confirm:
  path: /password-reset/{token<%assert.token%>}
  controller: App\Controller\PasswordResetConfirmController
  methods: GET|POST

mollie_webhook:
  path: /mollie/webhook
  controller: App\Controller\MollieWebhookController
  methods: POST

mollie_checkout_anonymous:
  path: /mollie/checkout/{token<%assert.big_token%>}
  controller: App\Controller\MollieCheckoutAnonymousController
  methods: GET|POST

system_admin:
  prefix: /{role_short<%assert.role_short.admin%>}
  resource: system_admin.yaml

system_user:
  prefix: /{role_short<%assert.role_short.user%>}
  resource: system_user.yaml

system_guest:
  prefix: /{role_short<%assert.role_short.guest%>}
  resource: system_guest.yaml

system_init:
  prefix: /init
  resource: system_init.yaml

home:
  path: /
  controller: App\Controller\HomeController
  methods: GET
