status:
  controller: App\Controller\StatusController
  path: /status
  methods: GET
  defaults:
    module: status

categories_del:
  controller: App\Controller\Categories\CategoriesDelController
  path: /categories/{id<%assert.id%>}/del
  methods: GET|POST
  defaults:
    module: messages

categories_edit:
  controller: App\Controller\Categories\CategoriesEditController
  path: /categories/{id<%assert.id%>}/edit
  methods: GET|POST
  defaults:
    module: messages

categories_add:
  controller: App\Controller\Categories\CategoriesAddController
  path: /categories/add
  methods: GET|POST
  defaults:
    module: messages

categories:
  controller: App\Controller\Categories\CategoriesController
  path: /categories
  methods: GET|POST
  defaults:
    module: messages

contact_types_del:
  controller: App\Controller\ContactTypes\ContactTypesDelController
  path: /contact-types/{id<%assert.id%>}/del
  methods: GET|POST
  defaults:
    module: users

contact_types_edit:
  controller: App\Controller\ContactTypes\ContactTypesEditController
  path: /contact-types/{id<%assert.id%>}/edit
  methods: GET|POST
  defaults:
    module: users

contact_types_add:
  controller: App\Controller\ContactTypes\ContactTypesAddController
  path: /contact-types/add
  methods: GET|POST
  defaults:
    module: users

contact_types:
  controller: App\Controller\ContactTypes\ContactTypesController
  path: /contact-types
  methods: GET
  defaults:
    module: users

contacts_del_admin:
  controller: App\Controller\Contacts\ContactsDelAdminController
  path: /contacts/{id<%assert.id%>}/del
  methods: GET|POST
  defaults:
    module: users

contacts_edit_admin:
  controller: App\Controller\Contacts\ContactsEditAdminController
  path: /contacts/{id<%assert.id%>}/edit
  methods: GET|POST
  defaults:
    module: users

contacts_add_admin:
  controller: App\Controller\Contacts\ContactsAddAdminController
  path: /contacts/add
  methods: GET|POST
  defaults:
    module: users

contacts:
  controller: App\Controller\Contacts\ContactsAdminController
  path: /contacts
  methods: GET
  defaults:
    module: users

users_contacts_edit_admin:
  controller: App\Controller\UsersContacts\UsersContactsEditAdminController
  path: /users/{user_id<%assert.id%>}/contacts/{contact_id<%assert.id%>}/edit
  methods: GET|POST
  defaults:
    module: users

users_contacts_del_admin:
  controller: App\Controller\UsersContacts\UsersContactsDelAdminController
  path: /users/{user_id<%assert.id%>}/contacts/{contact_id<%assert.id%>}/del
  methods: GET|POST
  defaults:
    module: users

users_contacts_add_admin:
  controller: App\Controller\UsersContacts\UsersContactsAddAdminController
  path: /users/{user_id<%assert.id%>}/contacts/add
  methods: GET|POST
  defaults:
    module: users

config_name:
  controller: App\Controller\Config\ConfigNameController
  path: /config/name
  methods: GET|POST
  defaults:
    module: config

config_logo:
  controller: App\Controller\Config\ConfigLogoController
  path: /config/logo
  methods: GET|POST
  defaults:
    module: config

config_logo_upload:
  controller: App\Controller\Config\ConfigLogoUploadController
  path: /config/logo/upload/{image_token<%assert.token%>}
  methods: POST
  defaults:
    module: config

config_logo_del:
  controller: App\Controller\Config\ConfigLogoDelController
  path: /config/logo/del
  methods: GET|POST
  defaults:
    module: config

config_modules:
  controller: App\Controller\Config\ConfigModulesController
  path: /config/modules
  methods: GET|POST
  defaults:
    module: config

config_ext_modules:
  controller: App\Controller\ConfigExtModulesController
  path: /config/modules
  methods: GET|POST

config:
  controller: App\Controller\ConfigController
  path: /config/{tab<%assert.config_tab%>?system-name}
  methods: GET|POST
  defaults:
    module: config

intersystems_edit:
  controller: App\Controller\Intersystems\IntersystemsEditController
  path: /intersystems/{id<%assert.id%>}/edit
  methods: GET|POST
  defaults:
    module: intersystems

intersystems_del:
  controller: App\Controller\Intersystems\IntersystemsDelController
  path: /intersystems/{id<%assert.id%>}/del
  methods: GET|POST
  defaults:
    module: instersystems

intersystems_add:
  controller: App\Controller\Intersystems\IntersystemsAddController
  path: /intersystems/add
  methods: GET|POST
  defaults:
    module: intersystems

intersystems_show:
  controller: App\Controller\Intersystems\IntersystemsShowController
  path: /intersystems/{id<%assert.id%>}
  methods: GET
  defaults:
    module: intersystems

intersystems:
  controller: App\Controller\Intersystems\IntersystemsController
  path: /intersystems
  methods: GET
  defaults:
    module: intersystems

export:
  controller: App\Controller\ExportController
  path: /export
  methods: GET|POST
  defaults:
    module: export

autominlimit:
  controller: App\Controller\AutoMinLimitController
  path: /autominlimit
  methods: GET|POST
  defaults:
    module: transactions

mass_transaction:
  controller: App\Controller\MassTransactionController
  path: /mass-transaction
  methods: GET|POST
  defaults:
    module: transactions

messages_cleanup:
  controller: App\Controller\MessagesModules\MessagesCleanupController
  path: /messages/cleanup
  methods: GET|POST
  defaults:
    module: messages

messages_modules:
  controller: App\Controller\MessagesModules\MessagesModulesController
  path: /messages/modules
  methods: GET|POST
  defaults:
    module: messages

logs:
  controller: App\Controller\LogsController
  path: /logs
  methods: GET
  defaults:
    module: logs

users_image_del_admin:
  controller: App\Controller\UsersImage\UsersImageDelAdminController
  path: /users/{id<%assert.id%>}/image/del
  methods: GET|POST
  defaults:
    module: users

users_image_upload_admin:
  controller: App\Controller\UsersImage\UsersImageUploadAdminController
  path: /users/{id<%assert.id%>}/image/upload
  methods: POST
  defaults:
    module: users

users_password_set_admin:
  controller: App\Controller\Users\UsersPasswordSetAdminController
  path: /users/{id<%assert.id%>}/password
  methods: GET|POST
  defaults:
    module: users

users_del_admin:
  controller: App\Controller\Users\UsersDelAdminController
  path: /users/{id<%assert.id%>}/del
  methods: GET|POST
  defaults:
    module: users

users_edit_admin:
  controller: App\Controller\Users\UsersEditAdminController
  path: /users/{id<%assert.id%>}/edit
  methods: GET|POST
  defaults:
    module: users

users_add:
  controller: App\Controller\Users\UsersAddController
  path: /users/add
  methods: GET|POST
  defaults:
    module: users

transactions_edit:
  controller: App\Controller\Transactions\TransactionsEditController
  path: /transactions/{id<%assert.id%>}/edit
  methods: GET|POST
  defaults:
    module: transactions

news_add:
  controller: App\Controller\News\NewsAddController
  path: /news/add
  methods: GET|POST
  defaults:
    module: news

news_del:
  controller: App\Controller\News\NewsDelController
  path: /news/{id<%assert.id%>}/del
  methods: GET|POST
  defaults:
    module: news

news_edit:
  controller: App\Controller\News\NewsEditController
  path: /news/{id<%assert.id%>}/edit
  methods: GET|POST
  defaults:
    module: news

calendar_add:
  controller: App\Controller\CalendarAddController
  path: /calendar/add
  methods: GET|POST
  defaults:
    module: calendar

calendar_del:
  controller: App\Controller\CalendarDelController
  path: /calendar/{id<%assert.id%>}/del
  methods: GET|POST
  defaults:
    module: calendar

calendar_edit:
  controller: App\Controller\CalendarEditController
  path: /calendar/{id<%assert.id%>}/edit
  methods: GET|POST
  defaults:
    module: calendar

docs_edit:
  controller: App\Controller\Docs\DocsEditController
  path: /docs/{id<%assert.id%>}/edit
  methods: GET|POST
  defaults:
    module: docs

docs_del:
  controller: App\Controller\Docs\DocsDelController
  path: /docs/{id<%assert.id%>}/del
  methods: GET|POST
  defaults:
    module: docs

docs_add:
  controller: App\Controller\Docs\DocsAddController
  path: /docs/add
  methods: GET|POST
  defaults:
    module: docs

docs_map_edit:
  controller: App\Controller\Docs\DocsMapEditController
  path: /docs/map/{id<%assert.id%>}/edit
  methods: GET|POST
  defaults:
    module: docs

typeahead_doc_map_names:
  controller: App\Controller\Typeahead\TypeaheadDocMapNamesController
  path: /typeahead/{thumbprint<%assert.thumbprint%>}/doc-map-names
  methods: GET
  defaults:
    module: docs

typeahead_intersystem_mail_accounts:
  controller: App\Controller\TypeaheadIntersystemMailAccountsController
  path: /typeahead-intersystem-mail-accounts
  methods: GET

typeahead_log_types:
  controller: App\Controller\Typeahead\TypeaheadLogTypesController
  path: /typeahead/{thumbprint<%assert.thumbprint%>}/log-types
  methods: GET
  defaults:
    module: logs

transactions_sum_in:
  controller: App\Controller\TransactionsSumInController
  path: /transactions-sum-in/{days<%assert.id%>}
  methods: GET
  defaults:
    module: transactions

transactions_sum_out:
  controller: App\Controller\TransactionsSumOutController
  path: /transactions-sum-out/{days<%assert.id%>}
  methods: GET
  defaults:
    module: transactions

weighted_balances:
  controller: App\Controller\WeightedBalancesController
  path: /weighted-balances/{days<%assert.id%>}
  methods: GET
  defaults:
    module: transactions

static_content_image_upload:
  controller: App\Controller\StaticContentImageUploadController
  path: /static-content/image-upload
  methods: POST
  defaults:
    module: static_content

static_content:
  controller: App\Controller\StaticContentController
  path: /static-content
  methods: POST
  defaults:
    module: static_content

mollie_config:
  path: /mollie/config
  controller: App\Controller\Mollie\MollieConfigController
  methods: GET|POST
  defaults:
    module: mollie

mollie_payments_add:
  path: /mollie/payments/add/{status<%assert.account_status%>?active}
  controller: App\Controller\Mollie\MolliePaymentsAddController
  methods: GET|POST
  defaults:
    module: mollie

mollie_payments:
  path: /mollie/payments
  controller: App\Controller\Mollie\MolliePaymentsController
  methods: GET|POST
  defaults:
    module: mollie
