users_contacts_edit:
  controller: App\Controller\UsersContactsEditController
  path: /users/contacts/{contact_id<%assert.id%>}/edit
  methods: GET|POST

users_contacts_del:
  controller: App\Controller\UsersContactsDelController
  path: /users/contacts/{contact_id<%assert.id%>}/del
  methods: GET|POST

users_contacts_add:
  controller: App\Controller\UsersContactsAddController
  path: /users/contacts/add
  methods: GET|POST

support:
  controller: App\Controller\SupportController
  path: /support
  methods: GET|POST

messages_images_instant_del:
  controller: App\Controller\MessagesImagesInstantDelController
  path: /messages/{id<%assert.id%>}/images/{img<%assert.message_image%>}/{ext<%assert.message_image_ext%>}/del/{form_token<%assert.token%>}
  methods: POST

messages_images_del:
  controller: App\Controller\MessagesImagesDelController
  path: /messages/{id<%assert.id%>}/images/del
  methods: GET|POST

messages_edit_images_upload:
  controller: App\Controller\MessagesEditImagesUploadController
  path: /messages/{id<%assert.id%>}/images/upload/{form_token<%assert.token%>}
  methods: POST

messages_add_images_upload:
  controller: App\Controller\MessagesAddImagesUploadController
  path: /messages/images/upload/{form_token<%assert.token%>}
  methods: POST

messages_images_upload:
  controller: App\Controller\MessagesShowImagesUploadController
  path: /messages/{id<%assert.id%>}/images/upload
  methods: POST

messages_extend:
  controller: App\Controller\MessagesExtendController
  path: /messages/{id<%assert.id%>}/extend/{days<%assert.id%>}
  methods: GET

messages_del:
  controller: App\Controller\MessagesDelController
  path: /messages/{id<%assert.id%>}/del
  methods: GET|POST

messages_edit:
  controller: App\Controller\MessagesEditController
  path: /messages/{id<%assert.id%>}/edit
  methods: GET|POST

messages_add:
  controller: App\Controller\MessagesAddController
  path: /messages/add
  methods: GET|POST

users_image_del:
  controller: App\Controller\UsersImageDelController
  path: /users/image/del
  methods: GET|POST

users_image_upload:
  controller: App\Controller\UsersImageUploadController
  path: /users/image/upload
  methods: POST

users_password:
  controller: App\Controller\UsersPasswordController
  path: /users/password
  methods: GET|POST

users_edit:
  controller: App\Controller\UsersEditController
  path: /users/edit
  methods: GET|POST

transactions_add:
  controller: App\Controller\TransactionsAddController
  path: /transactions/add
  methods: GET|POST

news_add:
  controller: App\Controller\NewsAddController
  path: /news/add
  methods: GET|POST

forum_edit:
  controller: App\Controller\ForumEditController
  path: /forum/{id<%assert.id%>}/edit
  methods: GET|POST

forum_del:
  controller: App\Controller\ForumDelController
  path: /forum/{id<%assert.id%>}/del
  methods: GET|POST

forum_add_topic:
  controller: App\Controller\ForumAddTopicController
  path: /forum/add-topic
  methods: GET|POST

typeahead_account_codes:
  controller: App\Controller\TypeaheadAccountCodesController
  path: /typeahead-account-codes
  methods: GET

typeahead_usernames:
  controller: App\Controller\TypeaheadUsernamesController
  path: /typeahead-usernames
  methods: GET

typeahead_eland_intersystem_accounts:
  controller: App\Controller\TypeaheadElandIntersystemAccountsController
  path: /typeahead-eland-intersystem-accounts/{remote_schema<%assert.schema%>}
  methods: GET

typeahead_postcodes:
  controller: App\Controller\TypeaheadPostcodesController
  path: /typeahead-postcodes
  methods: GET
